server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/fintaxpro
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=yourSuperSecretKeyHere

# --- HIKARI CLEANUP (removes false warnings) ---
spring.datasource.hikari.leakDetectionThreshold=0
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=5000

# --- CLEAN LOG FORMAT ---
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} | %clr(%-5level){blue} | %clr(%logger{36}){cyan} | %clr(%msg){green}%n

